from enum import Enum


class CookieTypes(Enum):
    ACCEPT_CGU = 'ACCEPT_CGU'
    ACCEPT_SESSION_ON_DISCUSSION = 'ACCEPT_SESSION_ON_DISCUSSION'
    ACCEPT_TRACKING_ON_DISCUSSION = 'ACCEPT_TRACKING_ON_DISCUSSION'
    ACCEPT_PRIVACY_POLICY_ON_DISCUSSION = 'ACCEPT_PRIVACY_POLICY_ON_DISCUSSION'
    ACCEPT_LOCALE = 'ACCEPT_LOCALE'
    REJECT_LOCALE = 'REJECT_LOCALE'
    REJECT_CGU = 'REJECT_CGU'
    REJECT_SESSION_ON_DISCUSSION = 'REJECT_SESSION_ON_DISCUSSION'
    REJECT_TRACKING_ON_DISCUSSION = 'REJECT_TRACKING_ON_DISCUSSION'
    REJECT_PRIVACY_POLICY_ON_DISCUSSION = 'REJECT_PRIVACY_POLICY_ON_DISCUSSION'

    @classmethod
    def values(cls):
        return cls._member_names_
