from enum import Enum


class CookieTypes(Enum):
    ACCEPT_CGU = 'ACCEPT_CGU'
    ACCEPT_SESSION_ON_DISCUSSION = 'ACCEPT_SESSION_ON_DISCUSSION'
    ACCEPT_TRACKING_ON_DISCUSSION = 'ACCEPT_TRACKING_ON_DISCUSSION'
    ACCEPT_PRIVACY_POLICY_ON_DISCUSSION = 'ACCEPT_PRIVACY_POLICY_ON_DISCUSSION'
