from enum import Enum


class CookieTypes(Enum):
    ACCEPT_CGU = 'ACCEPT_CGU'
    ACCEPT_SESSION_ON_DISCUSSION = 'ACCEPT_SESSION_ON_DISCUSSION'
    ACCEPT_TRACKING_ON_DISCUSSION = 'ACCEPT_TRACKING_ON_DISCUSSION'
    ACCEPT_PRIVACY_POLICY_ON_DISCUSSION = 'ACCEPT_PRIVACY_POLICY_ON_DISCUSSION'
    ACCEPT_USER_GUIDELINE_ON_DISCUSSION = 'ACCEPT_USER_GUIDELINE_ON_DISCUSSION'
    ACCEPT_LOCALE = 'ACCEPT_LOCALE'
    REJECT_LOCALE = 'REJECT_LOCALE'
    REJECT_CGU = 'REJECT_CGU'
    REJECT_SESSION_ON_DISCUSSION = 'REJECT_SESSION_ON_DISCUSSION'
    REJECT_TRACKING_ON_DISCUSSION = 'REJECT_TRACKING_ON_DISCUSSION'
    REJECT_PRIVACY_POLICY_ON_DISCUSSION = 'REJECT_PRIVACY_POLICY_ON_DISCUSSION'
    REJECT_USER_GUIDELINE_ON_DISCUSSION = 'REJECT_USER_GUIDELINE_ON_DISCUSSION'

    @classmethod
    def values(cls):
        return cls._member_names_


# A list of cookies that are ACCEPTed
AcceptedCookies = {
    CookieTypes.ACCEPT_CGU,
    CookieTypes.ACCEPT_SESSION_ON_DISCUSSION,
    CookieTypes.ACCEPT_TRACKING_ON_DISCUSSION,
    CookieTypes.ACCEPT_PRIVACY_POLICY_ON_DISCUSSION,
    CookieTypes.ACCEPT_LOCALE,
    CookieTypes.ACCEPT_USER_GUIDELINE_ON_DISCUSSION
}

# A list of cookies that are REJECTed
RejectedCookies = {
    CookieTypes.REJECT_LOCALE,
    CookieTypes.REJECT_CGU,
    CookieTypes.REJECT_SESSION_ON_DISCUSSION,
    CookieTypes.REJECT_TRACKING_ON_DISCUSSION,
    CookieTypes.REJECT_PRIVACY_POLICY_ON_DISCUSSION,
    CookieTypes.REJECT_USER_GUIDELINE_ON_DISCUSSION
}
