"""Add MailingList source, subject mangling

Revision ID: 16375b22bb0f
Revises: 1c439fb5654e
Create Date: 2013-10-01 17:14:28.632461

"""

# revision identifiers, used by Alembic.
revision = '16375b22bb0f'
down_revision = '1c439fb5654e'

from alembic import context, op
import sqlalchemy as sa
import transaction

from assembl.lib import config


def upgrade(pyramid_env):
    with context.begin_transaction():
        ### commands auto generated by Alembic - please adjust! ###
        op.create_table('source_mailinglist',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('post_email_address', sa.UnicodeText(), nullable=True),
        sa.ForeignKeyConstraint(['id'], ['mailbox.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        op.add_column(u'mailbox', sa.Column('subject_mangling_regex', sa.UnicodeText(), nullable=True))
        op.add_column(u'mailbox', sa.Column('subject_mangling_replacement', sa.UnicodeText(), nullable=True))
        ### end Alembic commands ###

    # Do stuff with the app's models here.
    with transaction.manager:
        pass


def downgrade(pyramid_env):
    with context.begin_transaction():
        ### commands auto generated by Alembic - please adjust! ###
        op.drop_column(u'mailbox', 'subject_mangling_replacement')
        op.drop_column(u'mailbox', 'subject_mangling_regex')
        op.drop_table('source_mailinglist')
        ### end Alembic commands ###
