"""Proper sqlalchemy polymorphism for the auth module

Revision ID: 1c439fb5654e
Revises: 3fc4f31ea2
Create Date: 2013-09-27 18:30:50.637634

"""

# revision identifiers, used by Alembic.
revision = '1c439fb5654e'
down_revision = '3fc4f31ea2'

from alembic import context, op
import sqlalchemy as sa
import transaction


from assembl import models as m
from assembl.lib import config

db = m.DBSession


def upgrade(pyramid_env):
    with context.begin_transaction():
        ### commands auto generated by Alembic - please adjust! ###
        op.create_table('abstract_agent_account',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('type', sa.String(length=60), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.rename_table(u'email_account', 'agent_email_account')
        op.rename_table(u'idprovider_account', 'idprovider_agent_account')
        op.execute("INSERT INTO abstract_agent_account (id) (SELECT id FROM agent_email_account)")
        op.execute("UPDATE abstract_agent_account SET type='agent_email_account'")
        op.execute("select setval('abstract_agent_account_id_seq', (SELECT max(id)+1 FROM abstract_agent_account), false)")
        op.create_foreign_key('fk_id','agent_email_account', 'abstract_agent_account', ['id'], ['id'], ondelete='CASCADE')
        op.create_foreign_key('fk_id','idprovider_agent_account', 'abstract_agent_account', ['id'], ['id'], ondelete='CASCADE')

        ### end Alembic commands ###

    # Do stuff with the app's models here.
    with transaction.manager:
        pass


def downgrade(pyramid_env):
    with context.begin_transaction():
        ### commands auto generated by Alembic - please adjust! ###
        pass
        ### end Alembic commands ###
