"""Remove all size restrictions

Revision ID: 2392157306a8
Revises: 42a76adf343c
Create Date: 2013-09-25 13:21:31.057160

"""

# revision identifiers, used by Alembic.
revision = '2392157306a8'
down_revision = '42a76adf343c'

from alembic import context, op
import sqlalchemy as sa
import transaction


from assembl import models as m
from assembl.lib import config

db = m.DBSession


def upgrade(pyramid_env):
    with context.begin_transaction():
        ### commands auto generated by Alembic - please adjust! ###
        op.alter_column('discussion', 'topic', type_=sa.UnicodeText)
        op.alter_column('discussion', 'slug', type_=sa.UnicodeText)
        op.alter_column('synthesis', 'subject', type_=sa.UnicodeText)
        op.alter_column('idea', 'long_title', type_=sa.UnicodeText)
        op.alter_column('idea', 'short_title', type_=sa.UnicodeText)
        op.alter_column('source', 'name', type_=sa.UnicodeText)
        op.alter_column('mailbox', 'username', type_=sa.UnicodeText)
        op.alter_column('mailbox', 'password', type_=sa.UnicodeText)
        op.alter_column('mailbox', 'folder', type_=sa.UnicodeText)
        op.alter_column('mailbox', 'last_imported_email_uid', type_=sa.UnicodeText)
        ### end Alembic commands ###

    # Do stuff with the app's models here.
    with transaction.manager:
        pass


def downgrade(pyramid_env):
    with context.begin_transaction():
        ### commands auto generated by Alembic - please adjust! ###
        pass
        ### end Alembic commands ###
