"""Change link storage table to we don't have a chicken and the egg problem at creation

Revision ID: 314c93b20f51
Revises: 5440671667e9
Create Date: 2013-08-05 16:34:28.513932

"""

# revision identifiers, used by Alembic.
revision = '314c93b20f51'
down_revision = '5440671667e9'

from alembic import context, op
import sqlalchemy as sa
import transaction


from assembl import models as m
from assembl.lib import config

db = m.DBSession


def upgrade(pyramid_env):
    with context.begin_transaction():
        ### commands auto generated by Alembic - please adjust! ###
        op.add_column('discussion', sa.Column('table_of_contents_id', sa.Integer(), nullable=True))
        op.alter_column('discussion', 'table_of_contents_id', nullable=False)
        op.drop_column('table_of_contents', u'discussion_id')
        ### end Alembic commands ###

    # Do stuff with the app's models here.
    with transaction.manager:
        pass


def downgrade(pyramid_env):
    with context.begin_transaction():
        ### commands auto generated by Alembic - please adjust! ###
        op.add_column('table_of_contents', sa.Column(u'discussion_id', sa.INTEGER(), nullable=False))
        op.drop_column('discussion', 'table_of_contents_id')
        ### end Alembic commands ###
