"""extract.source is non-nullable

Revision ID: 3b3547b5030a
Revises: 511e922654ed
Create Date: 2013-08-18 17:54:19.844431

"""

# revision identifiers, used by Alembic.
revision = '3b3547b5030a'
down_revision = '511e922654ed'

from alembic import context, op
import sqlalchemy as sa
import transaction


from assembl import models as m
from assembl.lib import config


def upgrade(pyramid_env):
    with context.begin_transaction():
        ### commands auto generated by Alembic - please adjust! ###
        op.alter_column('extract', u'source_id',
                   existing_type=sa.INTEGER(),
                   nullable=False)
        ### end Alembic commands ###

    # Do stuff with the app's models here.
    with transaction.manager:
        pass


def downgrade(pyramid_env):
    with context.begin_transaction():
        ### commands auto generated by Alembic - please adjust! ###
        op.alter_column('extract', u'source_id',
                   existing_type=sa.INTEGER(),
                   nullable=True)
        ### end Alembic commands ###
