"""post 'is synthesis' field

Revision ID: 3fc4f31ea2
Revises: 2392157306a8
Create Date: 2013-09-25 16:07:05.244144

"""

# revision identifiers, used by Alembic.
revision = '3fc4f31ea2'
down_revision = '2392157306a8'

from alembic import context, op
import sqlalchemy as sa
import transaction


from assembl import models as m
from assembl.lib import config


def upgrade(pyramid_env):
    with context.begin_transaction():
        ### commands auto generated by Alembic - please adjust! ###
        op.add_column('post', sa.Column('is_synthesis', sa.Boolean(), nullable=True))
        ### end Alembic commands ###

    # Do stuff with the app's models here.
    with transaction.manager:
        pass


def downgrade(pyramid_env):
    with context.begin_transaction():
        ### commands auto generated by Alembic - please adjust! ###
        op.drop_column('post', 'is_synthesis')
        ### end Alembic commands ###
