"""extract.owner_id and extract.creator_id required

Revision ID: 511e922654ed
Revises: 1f8852d18bbd
Create Date: 2013-08-17 21:24:16.489764

"""

# revision identifiers, used by Alembic.
revision = '511e922654ed'
down_revision = '1f8852d18bbd'

from alembic import context, op
import sqlalchemy as sa
import transaction

from assembl.lib import config


def upgrade(pyramid_env):
    with context.begin_transaction():
        ### commands auto generated by Alembic - please adjust! ###
        op.alter_column('extract', u'creator_id',
                   existing_type=sa.INTEGER(),
                   nullable=False)
        op.alter_column('extract', u'owner_id',
                   existing_type=sa.INTEGER(),
                   nullable=False)
        ### end Alembic commands ###

    # Do stuff with the app's models here.
    with transaction.manager:
        pass


def downgrade(pyramid_env):
    with context.begin_transaction():
        ### commands auto generated by Alembic - please adjust! ###
        op.alter_column('extract', u'owner_id',
                   existing_type=sa.INTEGER(),
                   nullable=True)
        op.alter_column('extract', u'creator_id',
                   existing_type=sa.INTEGER(),
                   nullable=True)
        ### end Alembic commands ###
