#!/bin/bash -e

url=$1
source_branch=$2
target_branch=$3

git merge ${target_branch:-master}
git checkout ${target_branch:-master}
git merge ${source_branch:-origin/develop}
git push $url --force
exit 0