_extends: base_env.yaml
ini_files: production.ini no_sentry.ini RANDOM:random.ini.tmpl:saml_random.ini.tmpl RC_DATA
DEFAULT:
  db_user: assembl_user
  sentry_host: sentry-aws.bluenove.com
hosts: localhost
attachment_service: s3
celery_tasks.broker: sqs://
rds_certificate: rds-combined-ca-bundle.pem
aws_region: eu-west-1
aws_shared_region: eu-west-1
attachment_bucket: "assembl-data-%(aws_client)s"
elasticsearch_index: "%(aws_client)s:assembl-es"
elasticsearch_port: 80
elasticsearch_version: 5.6.8
mail.port: 587
aws_secrets_ids:
  - arn:aws:secretsmanager:eu-west-1:900208097337:secret:assembl_shared_secrets-8cUP7z
  - assembl_secrets
supervisor:
  autostart_celery: false
  autostart_celery_notify_beat: false
  autostart_source_reader: false
  autostart_changes_router: false
  autostart_urlmetadata: false
  autostart_elasticsearch: false
db_iam_role: "arn:aws:iam::%(aws_client)s:role/AssemblEC2Role"
handlers:
  keys: console, file, cloudwatch
handler_cloudwatch:
  class: watchtower.CloudWatchLogHandler
  args: ('AssemblLogs', 'Log', True, 10)
  formatter: json
  level: INFO
logger_root:
  handlers: file, cloudwatch
logger_assembl:
  handlers: file, cloudwatch
logger_sqlalchemy:
  handlers: file, cloudwatch
uwsgi_port: 3001
uwsgi_host: localhost
uwsgi:
  socket: :3001
  stats: :3002
  stats-http: 1

public_port: 80
accept_secure_connection: false
require_secure_connection: false
piwik_host: stats.bluenove.com
csp_header: |-
  default-src 'self' www.bugherd.com; script-src 'self' 'unsafe-inline' 'unsafe-eval' data: %(piwik_host)s *.facebook.net *.twimg.com *.twitter.com *.bugherd.com *.cloudfront.net; frame-src 'self' www.youtube.com *.facebook.com embed.ted.com *.twitter.com twitter.com player.vimeo.com www.bugherd.com *.coggle.it mindjet.com *.mindmanager.com *.slideshare.net; connect-src 'self' wss://%(public_hostname)s %(sentry_host)s %(piwik_host)s *.twitter.com www.bugherd.com *.pusher.com bugherd-attachments.s3.amazonaws.com; style-src 'self' 'unsafe-inline' fonts.googleapis.com *.twimg.com *.twitter.com www.bugherd.com *.cloudfront.net s3-eu-west-1.amazonaws.com stackpath.bootstrapcdn.com; font-src 'self' data: fonts.gstatic.com www.bugherd.com bluenove-assembl-fonts.s3-eu-west-1.amazonaws.com; img-src 'self' data: %(piwik_host)s *.facebook.com www.gravatar.com *.googleusercontent.com *.twimg.com *.twitter.com framapic.org *.cloudfront.net img.youtube.com www.bugherd.com
wheelhouse: s3://bluenove-assembl-wheelhouse
secure_proxy: true
alembic:
  script_location: "%(code_root)s/alembic"
